/-
Live coverage guard for the axiom-pinning contract in `scripts/print_axioms.lean`
(Issue #56). Walks the fully elaborated environment produced by `lake build` and fails
unless every public `theorem` declared inside a `MobiusCPT…` module has a
`#print axioms` line in `scripts/print_axioms.lean` (the input consumed at run time by
`scripts/check-axioms.sh`, the live trust-footprint audit).

Run via `lake env lean scripts/check_axiom_coverage.lean` from the repository root
(`scripts/check-axiom-coverage.sh` wraps this; `scripts/check.sh` runs it immediately
after the live axiom audit, under the same `/tmp/lean-build.lock` as the rest of the
gate — this walk costs roughly the same memory as that audit run).

No Lean statement in `MobiusCPT/` is read or altered here; only `ConstantInfo`
metadata already produced by `lake build` is inspected.

"Public theorem" excludes every one of the following kinds — each a legitimate,
non-claimed `.thmInfo` declaration Lean/Mathlib elaboration produces, not a
mathematical result a PR is claiming as a result:

  * `private` declarations                                    — `isPrivateName`
  * internal/auxiliary names: a leading `_` component, or an
    `eq_`/`match_`/`proof_`/`omega_` component, or any numeric
    component                                                  — `Name.isInternalDetail`
  * auxiliary recursors (`recOn`/`casesOn`/`brecOn`-style
    helpers tagged by the elaborator, plus `Eq.ndrec` &c.)      — `isAuxRecursor`
  * `structure`/`inductive`-generated theorem suffixes the
    two checks above do not catch: `.injEq`, `.ext`, `.ext_iff`,
    `.sizeOf_spec`, `.noConfusion`, `.noConfusionType`, any
    `.mk.*` accessor, or the auto-generated `simp`-congruence
    lemma suffix `.congr_simp`                                   — `hasStructureGeneratedComponent`
  * `structure`/`class` field projections — a `Prop`-valued
    field of a `structure`/`class ... where` block elaborates as
    a `theorem`-kind projection function (e.g. `WightmanData.U_mul`,
    `MobiusAction.beta_mul`, `IsRapidlyDecaying.contDiff`); these
    are mechanical accessors, not independently claimed results   — `Environment.isProjectionFn`
  * `instance` declarations, which elaborate as `theorem`s
    when Prop-valued                                            — `Lean.Meta.isInstance`

Iterate this list, not the caller, if a false positive or false negative shows up:
every excluded kind above must stay listed here.
-/
import MobiusCPT

open Lean

/-- Name components generated by `structure`/`inductive` elaboration that
`Name.isInternalDetail` does not catch (they don't start with `_` and aren't
`eq_`/`match_`/`proof_`/`omega_`), but are never a claimed public result. -/
private def isStructureGeneratedComponent (s : String) : Bool :=
  s == "injEq" || s == "ext" || s == "ext_iff" || s == "sizeOf_spec" ||
  s == "noConfusion" || s == "noConfusionType" || s == "mk" || s == Lean.Meta.congrSimpSuffix

/-- Does any dotted component of `n` match a structure-generated suffix? -/
private def hasStructureGeneratedComponent : Name → Bool
  | .str p s => isStructureGeneratedComponent s || hasStructureGeneratedComponent p
  | .num p _ => hasStructureGeneratedComponent p
  | .anonymous => false

/-- `n` was declared in a module named `MobiusCPT`, or a submodule of it
(`MobiusCPT.Wightman.Basic`, the root aggregator `MobiusCPT`, etc). -/
private def isMobiusModule (env : Environment) (n : Name) : Bool :=
  match env.getModuleIdxFor? n with
  | some idx =>
    match env.header.moduleNames[idx.toNat]? with
    | some modName => (`MobiusCPT).isPrefixOf modName
    | none => false
  | none => false

/-- `n`/`info` is a public theorem this repository must pin in
`scripts/print_axioms.lean`. -/
private def isPublicMobiusTheorem (env : Environment) (n : Name) (info : ConstantInfo) :
    CoreM Bool := do
  match info with
  | .thmInfo _ =>
    if isPrivateName n then return false
    if n.isInternalDetail then return false
    if isAuxRecursor env n then return false
    if hasStructureGeneratedComponent n then return false
    if env.isProjectionFn n then return false
    if !isMobiusModule env n then return false
    if (← Lean.Meta.isInstance n) then return false
    return true
  | _ => return false

/-- The declaration names pinned by `#print axioms <name>` lines in `path`. -/
private def readPinnedNames (path : System.FilePath) : IO (Std.HashSet String) := do
  let contents ← IO.FS.readFile path
  let names := (contents.splitOn "\n").filterMap fun line =>
    match line.trim.splitOn " " |>.filter (· ≠ "") with
    | "#print" :: "axioms" :: name :: _ => some name
    | _ => none
  return Std.HashSet.ofList names

#eval show CoreM Unit from do
  let env ← getEnv
  let pinned ← readPinnedNames "scripts/print_axioms.lean"
  let mut total : Nat := 0
  let mut missing : Array String := #[]
  for (n, info) in env.constants.toList do
    if (← isPublicMobiusTheorem env n info) then
      total := total + 1
      let name := n.toString
      unless pinned.contains name do
        missing := missing.push name
  if missing.isEmpty then
    IO.println s!"COVERAGE OK — {total} public theorems, all pinned"
  else
    for name in missing.qsort (· < ·) do
      IO.println s!"MISSING: {name}"
    -- `throwError`, not `IO.Process.exit`: the latter terminates the process
    -- immediately and was observed (in review) to discard the `MISSING:` lines
    -- printed just above when stdout is not a terminal (as under `lake env lean`
    -- here). `throwError` reports through Lean's own elaboration-error channel,
    -- which both prints reliably and gives `lean`/`lake env lean` a nonzero exit
    -- code, the same mechanism `scripts/check-axioms.sh` already relies on when
    -- `lake env lean scripts/print_axioms.lean` fails.
    throwError s!"{missing.size} public theorem(s) declared in a MobiusCPT module are not pinned in scripts/print_axioms.lean (see MISSING: lines above)"
